version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pbr
    versions:
    - 5.5.1
  - dependency-name: tensorboard
    versions:
    - 2.4.1
